### PR TITLE
Add documentation for operators expecting sequence inputs

### PR DESCRIPTION
**Pull request by jantonguirao**
Signed-off-by: Joaquin Anton <janton@nvidia.com>

### CODE REVIEW

**Comment by jantonguirao** [comment]
Build #628971

**Comment by JanuszL** [comment]
Can you drop here screenshot how docs looks like with this change?

**Comment by jantonguirao** [comment]
@JanuszL 
screenshot from 2019-02-12 09-33-03

**Comment by jantonguirao** [comment]
Build 631627

**Comment by jantonguirao** [comment]
Build 631663

**Comment by jantonguirao** [comment]
Build 632636

**Pull request merged**
