### PR TITLE
Add optimized variant of CMN for HWC to HWC pad FP16 case

### PR DESCRIPTION
**Pull request by klecki**
## Description:
Introduce an optimized kernel for the HWC -> HWC, pad case for FP16.
With current DALI allocation patterns, all outputs are aligned to multiple of 4,
allowing to implement the output loop as writing pair of two lower channels, pair of two higher channels
for each pixel using vectorized fp16 instructions, resulting in 4 byte accesses to output gmem.

This yields up to 3x speedups compared to the previous version used by DALI for this particular case.
There is a safety fallback in case if the memory is not actually alinged.

### Affected modules and functionalities:
CMN 

### Tests:

- [x] Existing tests apply
This is already covered by existing tests, current implementation gets more specialized version
for one particular case.
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Review by awolant — APPROVED** [review]
Very nice comments and docs. This is quite hard code - additional info makes it significantly easier to understand.

**Review by szalpal — APPROVED** [review]

**Pull request merged**
