### PR TITLE
Fix Paddle plugin dev_id bug

### PR DESCRIPTION
**Pull request by sneaxiy**
## Description
- [x] **Bug fix** (*non-breaking change which fixes an issue*)
- [ ] **New feature** (*non-breaking change which adds functionality*)
- [ ] **Breaking change** (*fix or feature that would cause existing functionality to not work as expected*)
- [ ] **Refactoring** (*Redesign of existing code that doesn't affect functionality*)
- [ ] **Other** (*e.g. Documentation, Tests, Configuration*)

### What happened in this PR

DALI Paddle plugin supports multi-device data loading. The https://github.com/NVIDIA/DALI/pull/3487 does not consider this  when getting the right cuda stream.

#### Additional information
- Affected modules and functionalities: DALI Paddle plugin

- Key points relevant for the review: correct DALI Paddle plugin device id when calling `paddle.device.cuda.current_stream()`.

### Tests
- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Review by JanuszL — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Review by banasraf — APPROVED** [review]

**Comment by sneaxiy** [comment]
@JanuszL Hi, I found that the CI failed, but I cannot see the error message. Could you please tell me what is the error message?

**Comment by JanuszL** [comment]
> @JanuszL Hi, I found that the CI failed, but I cannot see the error message. Could you please tell me what is the error message?

Hi @sneaxiy,

It is our internal error related to the CI infra. I have relaunched failing test. It looks good so far. When CI passes I will merge your change. Thank you for your contribution.

**Comment by sneaxiy** [comment]
> > @JanuszL Hi, I found that the CI failed, but I cannot see the error message. Could you please tell me what is the error message?
> 
> Hi @sneaxiy,
> 
> It is our internal error related to the CI infra. I have relaunched failing test. It looks good so far. When CI passes I will merge your change. Thank you for your contribution.

@JanuszL Great! Thanks for your help!

**Comment by JanuszL** [comment]
@sneaxiy - thank you for a quick fix.

**Pull request merged**
