### PR TITLE
Add JAX Getting Started Tutorial

### PR DESCRIPTION
**Pull request by awolant**
## Category:

**New feature**

## Description:

Adds Getting Started Tutorial for JAX and DALI.

### Affected modules and functionalities:

JAX documentation.

### Key points relevant for the review:

Grammar, punctuation. Is it understandable?

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3669

### CODE REVIEW

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5095/discussion/#comment-1759895321'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
!build

**Review by jantonguirao — APPROVED** [review]

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5095/discussion/#comment-1759895361'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5095/discussion/#comment-1768470236'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5095/discussion/#comment-1768470193'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5095/discussion/#comment-1768470149'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
!build

**Review by szalpal — APPROVED** [review]

**Pull request merged**
