### PR TITLE
Bump nvJpeg to 0.1.4

### PR DESCRIPTION
**Pull request by JanuszL**
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by jxmelody** [comment]
Have nvJpeg updated to 0.1.4? The version in NVIDIA official web page is still nvJpeg 0.1.3...

**Comment by JanuszL** [comment]
Hi,
Page update stucked somewhere but it should be updated now.
Please check now.
Janusz

**Comment by jxmelody** [comment]
Thanks!
Yes,It update now.
I have one more question about nvJpeg——do you know how to use nvJpeg with multi-stream? I use multi-stream(cuda stream), but it can't work parallelly.   
so my question is: **About this performance report, how many core threads in CPU test and how many streams in GPU test?**  
image
PS. I found no where to ask questions about nvJpeg...so I asked here. Any reply would be very helpful, thanks!

**Comment by JanuszL** [comment]
Answer feom our nvJpeg guys:
Q:
> do you know how to use nvJpeg with multi-stream? I use multi-stream(cuda stream), but it can't work parallelly.
A:
There is stream parameter to all nvjpeg API's. What is not working specifically?
Q:
About this performance report, how many core threads in CPU test and how many streams in GPU test?
A:
1 core and 1 GPU stream. Turbojpeg is not multithreaded, but both nvJPEG and turbojpeg can be used in multithreaded environment to decode images in batches. Scaling of performance depends on a specific CPU used, and number of threads for both nvJPEG and Turbojpeg. For nvJPEG, of course, performance and scaling depends on GPU used. This chart was done with nvJPEG v0.1.0.

Official place for libraries questions is nvidia devtalks forums, how about trying this one?

**Comment by ptrendx** [comment]
Since nvJPEG is a hybrid approach (part of the computation is done on the CPU and part on the GPU) it needs to synchronize between CPU and GPU. That is why to have overlap between different streams you need to launch nvJPEG from multiple CPU threads (where each CPU thread takes a single stream).
Please see https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/decoder/nvjpeg_decoder.h for reference.

**Comment by JanuszL** [comment]
@jxmelody - please post further questions regarding nvJpeg inside nvidia devtalks forums as nvJpeg developers doen't track closely DALI project posts.

**Comment by jxmelody** [comment]
Yes, I think I should post further questions on NVIDIA devtalks forums.
You have helped me a lot ! @JanuszL @ptrendx. 
Thanks~

**Pull request merged**
