### PR TITLE
Fix numerical issue in clamping cropped bounding boxes.

### PR DESCRIPTION
**Pull request by mzient**
Signed-off-by: Michal Zientkiewicz <michalz@nvidia.com>

### CODE REVIEW

**Comment by guanfuchen** [comment]
RandomBBoxCrop has the same problem, can the RandomBBoxCrop and slice be replaced by SSDRandomCrop?

**Comment by guanfuchen** [comment]
This is my try to fix [RandomCrop](https://github.com/NVIDIA/DALI/blob/master/dali/pipeline/operators/crop/bbox_crop.cc#L123)

```
    float x1;
    float y1;
    float x2;
    float y2;
    if(ltrb_) {
        x1 = box_data[0];
        y1 = box_data[1];
        x2 = box_data[2];
        y2 = box_data[3];
    } else {
        x1 = box_data[0];
        y1 = box_data[1];
        x2 = box_data[2]+box_data[0];
        y2 = box_data[3]+box_data[1];
    }
    x1 = std::min(std::max(x1, 0.0f), 1.0f);
    y1 = std::min(std::max(y1, 0.0f), 1.0f);
    x2 = std::min(std::max(x2, 0.0f), 1.0f);
    y2 = std::min(std::max(y2, 0.0f), 1.0f);
    bounding_boxes.emplace_back(BoundingBox::FromLtrb(x1, y1, x2, y2));
    //auto box = ltrb_ ? BoundingBox::FromLtrb(box_data) : BoundingBox::FromXywh(box_data);
    //bounding_boxes.emplace_back(box);
  }

```

**Comment by mzient** [comment]
Formally, this is OK, but I think it's better to move the clamping to the constructor, instead of throwing exceptions from there.

**Comment by JanuszL** [comment]
In addition, we are currently in the middle of operator refactoring and moving it to the new API. We will do it when BBox operators are reworked. @guanfuchen - thanks for pointing that out. In the meantime feel free to prepare a PR if you like.

**Pull request merged**
