### PR TITLE
Align SSDRandom crop with RandomBBoxCrop + Slice

### PR DESCRIPTION
**Pull request by JanuszL**
- fixed discrepancies in random bbox cropping and image slicing

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by JanuszL** [comment]
Builds 657993

**Comment by JanuszL** [comment]
Builds 657999

**Comment by JanuszL** [comment]
Rebuilds 658785.

**Comment by awolant** [comment]
Maybe the same should be done for GPU slice for conformity?

**Comment by JanuszL** [comment]
> Maybe the same should be done for GPU slice for conformity?

I have missed that. Will fix that too.

**Comment by JanuszL** [comment]
Builds 658996

**Comment by JanuszL** [comment]
Build with shorter tests 659050

**Comment by JanuszL** [comment]
Rebuilds 660181

**Pull request merged**
