### PR TITLE
Format DALI with black

### PR DESCRIPTION
**Pull request by klecki**
## Description:
Format DALI with `black`. 
Adjust several docstrings that were too long in normalized form.
Add parentheses in yield expressions when they are too long,
so that black can break them into multi-line statements.
Fix autograph AST tests that relied on specific tab-width.
Remove some obsolete `# noqa: E501`. 

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Review by banasraf — APPROVED** [review]

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Review by szalpal — APPROVED** [review]
👍🏻 Thanks for taking care of it

**Comment by klecki** [comment]
!build

**Pull request merged**
