### PR TITLE
Update docs for `fill_last_batch` parameter to match the real behavior

### PR DESCRIPTION
**Pull request by bonlime**
#### Why we need this PR?
- [x] It fixes a bug
- It adds new feature needed because *why we need this feature*
- Refactoring to improve *what*

#### What happened in this PR?
Fixed `fill_last_batch` parameter docstring to match the real behavior

### CODE REVIEW

**Comment by bonlime** [comment]
would changing

> Whether to fill the last batch with data from next epoch

to 

> Whether to fill the last batch with data up to 'self.batch_size'

make it more accurate? I do understand that a combination of these 3 parameters may produce unexpected behavior but I think that it's enough to say what one parameter changes and everything else is explained in the table at the end of the docstring

**Comment by JanuszL** [comment]
> would changing
> 
> > Whether to fill the last batch with data from next epoch
> 
> to
> 
> > Whether to fill the last batch with data up to 'self.batch_size'
> 
> make it more accurate? I do understand that a combination of these 3 parameters may produce unexpected behavior but I think that it's enough to say what one parameter changes and everything else is explained in the table at the end of the docstring

I agree with the new wording. Please adjust accordingly.

**Comment by JanuszL** [comment]
@bonlime - can you add a sign-off to your commit so we can merge it?

**Comment by bonlime** [comment]
Okay. I have to admit I don't know how to sign previous commits :c

**Comment by JanuszL** [comment]
That is enough. Thanks for the contribution!

**Pull request merged**
