### PR TITLE
Support checkpointing in PaddlePaddle iterator

### PR DESCRIPTION
**Pull request by szkarpinski**
## Category:

**New feature** (*non-breaking change which adds functionality*)

## Description:
Checkpointing support was already implemented in `BaseIterator` in https://github.com/NVIDIA/DALI/pull/5061, but wasn't tested for frameworks other than Pytorch. In this PR I add tests for PaddlePaddle Iterator and fix a problem with ES checkpointing. This work is very similar to #5282 

When an iterator is created and there's no data in the external source, DALI reports "no data in pipeline" error. The problem is that if we checkpoint after the last iteration and restore from such checkpoint, there's no data in the external source but it's not an error. In this PR I silence this error if we're restoring from checkpoint. Exactly the same change was made in https://github.com/NVIDIA/DALI/pull/5213 and #5282 

### Affected modules and functionalities:

PaddlePaddle Iterator

### Tests:

- [ ] Existing tests apply
- [x] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3751

### CODE REVIEW

**Review by klecki — APPROVED** [review]

**Review by banasraf — APPROVED** [review]

**Comment by szkarpinski** [comment]
@klecki @banasraf Thanks for the approvals, I'll merge https://github.com/NVIDIA/DALI/pull/5298 first and then this one

**Comment by szkarpinski** [comment]
#5298 is now merged. To make this PR work I needed to make add `supported_last_batch_policies` method to `TestPaddle`. 

Also, [I needed to remove](https://github.com/NVIDIA/DALI/pull/5279/commits/59a8495ddbcd20673ac89bf7e83b3f86bac02d66) `self.counter_ = 0` from iterator's `__init__`. This was overwriting the counter restored in ` _DaliBaseIterator.__init__`. Paddle iterator was added long time ago (#1371) and there was no ` _DaliBaseIterator` at that moment, so Paddle iterator needed to handle the counter on its own. When ` _DaliBaseIterator` was introduced (#1831), this `self._counter = 0` was duplicated and not removed from Paddle iterator. It was redundant, but didn't cause any problems, until now. So in my understanding removing it is safe.

I'd be grateful for re-approval for that

**Comment by szkarpinski** [comment]
!build

**Comment by szkarpinski** [comment]
!build

**Comment by szkarpinski** [comment]
@banasraf @klecki I've successfully rebased on #5298, but with one non-trivial change. It turned out that `self.counter_` was reset to 0 by Paddle iterator, overwriting the value restored in `_DaliBaseIterator.__init__`. I [removed](https://github.com/NVIDIA/DALI/pull/5279/commits/59a8495ddbcd20673ac89bf7e83b3f86bac02d66) this line. 

When Paddle iterator was added (#1371), there was no `_DaliBaseIterator`, so the iterator needed to handle the counter on its own. When `_DaliBaseIterator` was created (#1831), ` `self.counter_ = 0` was duplicated. It was redundant in Paddle, but didn't cause problems until now.

Can I ask for re-approval for that?

**Review by banasraf — APPROVED** [review]

**Pull request merged**
