### PR TITLE
Bump version to 0.2

### PR DESCRIPTION
**Pull request by ptrendx**
Signed-off-by: ptredak <ptredak@nvidia.com>

### CODE REVIEW

**Comment by JanuszL** [comment]
I think we need to have only one file with version and we need to insert value form it to all other configs and readmes or we will always miss this one last place.

**Comment by ptrendx** [comment]
@JanuszL it will be hard for readme unfortunately since GitHub does not let you include anything in readme. For everything else I agree, will look into it on Monday.

**Comment by cliffwoolley** [comment]
Should the master branch README even list a version number?  Maybe we only add that on that branches?

**Comment by JanuszL** [comment]
I think we can skip it in the README if we have version file. I think other projects don't mention version in the readme.

**Comment by JanuszL** [comment]
Please look into https://github.com/NVIDIA/DALI/pull/85.

**Comment by ptrendx** [comment]
Closing in favor of #85

**Pull request closed without merging**
