### PR TITLE
Extend the documentation footer

### PR DESCRIPTION
**Pull request by JanuszL**
- makes the documentation footer aligned with the latest recommendations
- adds links with links related to privacy and terms of use in
  the documentation footer

## Category:
**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
- makes the documentation footer aligned with the latest recommendations
- adds links with links related to privacy and terms of use in
  the documentation footer

### Affected modules and functionalities:
- documentation template

### Key points relevant for the review:
- see https://docs.nvidia.com/deeplearning/dali/release-notes/index.html for the reference

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [x] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
image

**Review by szalpal — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
image

**Pull request merged**
