### PR TITLE
Add CUDA 10 based build

### PR DESCRIPTION
**Pull request by JanuszL**
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by szalpal** [comment]
Comment about `Dockerfile.deps` implementation:

* In this situation we have multiple layers of Docker Image created, while not all of them are acutally in use (either one or two of them will be just empty layers). I'd suggest to combine both 9.x and 10.x routines into one layer. In my opinion it is logically better concept to have every framework expanded on one layer tops. 
* Moreover, I suspect (I'm not 100% sure about it), that any change of ARG on line 15 will cause rebuilding of all underlying layers. Taking into consideration, that it is passed during `docker build`, we will have a lot of unnecessary build time. [Here's](https://docs.docker.com/engine/reference/builder/#impact-on-build-caching) more info on that. I think moving ARG declaration or using ENV directive could be alternative
* Also, such implementation requires user to provide correct `USE_CUDA_VERSION` argument during build (i.e. either `9` or `10`). Maybe we should make CUDA 9.x default version, built even if user wanted incorrect version of CUDA?

**Comment by cliffwoolley** [comment]
@szalpal is correct, except that `ARG USE_CUDA_VERSION=9` does provide a default value.  The ARG should be placed as close to its first use as possible, and the conditional RUNs can be combined.

**Comment by JanuszL** [comment]
I have combined all CUDA SDK stuff into one layer (including nvJpeg).

**Comment by JanuszL** [comment]
Builds 36106

**Comment by szalpal** [comment]
One last thing. If user calls docker with command, e.g. `docker build --build-arg USE_CUDA_VERSION=8`, he will not be prompted with message, that this particular CUDA version is not supported. The build in fact will succeed or fail on some random stuff. I think it would be nice to add at least a message for that

**Comment by JanuszL** [comment]
I can just fail docker build, it seems reasonable.

**Comment by JanuszL** [comment]
Done, builds 36144.

**Comment by JanuszL** [comment]
@cliffwoolley - cuda 8 has never been supported by us officially (community-based effort) and docker hasn't provided that ability, and it was possible only without nvJpeg in such case. This PR doesn't remove anything, just extends to CUDA 10 support. Soon we will turn on CUDA 10 as a default.

**Pull request merged**
