### PR TITLE
Improve PyPi DALI description

### PR DESCRIPTION
**Pull request by JanuszL**
## Category:
**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
- adds a link to the DALI documentation to the PyPi package description
- adds the DALI key visual

### Affected modules and functionalities:
- setup.py.in for DALI and TF plugin

### Key points relevant for the review:
- NA

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [x] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Review by klecki — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Review by klecki — APPROVED** [review]

**Review by stiepan — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
```
> twine check nvidia-dali-tf-plugin-cuda120-1.25.0.dev0.tar.gz
  Checking nvidia-dali-tf-plugin-cuda120-1.25.0.dev0.tar.gz: PASSED
> twine check nvidia_dali_cuda120-1.25.0.dev0-7836388-py3-none-manylinux2014_x86_64.whl
  Checking nvidia_dali_cuda120-1.25.0.dev0-7836388-py3-none-manylinux2014_x86_64.whl: PASSED
```
🤞

**Pull request merged**
