### PR TITLE
Rework Image Decoder example

### PR DESCRIPTION
**Pull request by JanuszL**
- Image Decoder examples (CPU) and Image Decoder (Hybrid)
  appear in the example list while they are just different
  sections of the same document. This PR makes sure that there
  is only one top-level header in the example
- reduces the amount of the repetitive code in the decoders
  example
- improves the example description

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

## Category:

**Bug fix** (*non-breaking change which fixes an issue*)

## Description:
- Image Decoder examples (CPU) and Image Decoder (Hybrid)
  appear in the example list while they are just different
  sections of the same document. This PR makes sure that there
  is only one top-level header in the example
- reduces the amount of the repetitive code in the decoders
  example
- improves the example description

### Affected modules and functionalities:
- image decoder example

### Key points relevant for the review:
- if the simplification is sufficient

### Tests
- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-1892

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
image

**Review by klecki — APPROVED** [review]

**Comment by JanuszL** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3731/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3731/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>Leftover</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3731/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3731/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3731/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
!build

**Pull request merged**
