### PR TITLE
Propagate module and display name of the operator to backend

### PR DESCRIPTION
**Pull request by klecki**
## Description:
Move module and op name partitioning to backend.
The "__" delimiter splitting of schema name into a module path and operator name is moved to backend.

Python APIs are switched over to query the schema.

ops.Compose is removed from registry of operators - it is mainly used to generate documentation and stubs, Compose is not really an operator but a special Python wrapper. It will be a standalone entity in the ops module and the documentation for it is now listed separately.

Add new `_module` and `_display_name` arguments that are updated by the `fn` and `ops` API bindings.

OpSpec name() is adjusted to SchemaName() to differentiate that from the name/display name
of the operator and avoid the confusion.

New module that formats module path and operator display name is added in the backend.

Tests are added on Python level, to see if the bindings correctly propagate the snake_case
and CamelCase names (with the proper API specified).

The tests is based on the origin stack trace tests, both are generalized into simple common utility.

In a followup those utilities will be used to report better error messages.

### Affected modules and functionalities:
API bindings generation - schema processing,
OpSpec and OpSchema APIs are adjusted and extended
New module for processing names in backend.
ops.Compose.

### Tests:

- [ ] Existing tests apply
- [x] New tests added
  - [x] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Review by banasraf — APPROVED** [review]

**Comment by klecki** [comment]
!build

**Review by mzient — APPROVED** [review]

**Pull request merged**
