### PR TITLE
Add multi gpu python notebook

### PR DESCRIPTION
**Pull request by awolant**
Signed-off-by: Albert Wolant <awolant@nvidia.com>

#### Why we need this PR?
- Refactoring to improve docs.

#### What happened in this PR?
 - What was changed, added, removed?
Add docs page about multiple GPU training in DALI.
 - Were docs and examples updated, if necessary?
It adds new docs page.

**JIRA TASK**: [NA]

Follow-up to #1175

### CODE REVIEW

**Comment by awolant** [comment]
!build

**Comment by JanuszL** [comment]
In the example it would be good to disable shuffling explicitly to show that images are different not because of it.

**Comment by awolant** [comment]
> In the example it would be good to disable shuffling explicitly to show that images are different not because of it.

Done

**Comment by awolant** [comment]
!build

**Comment by szalpal** [comment]
Quite a decent tutorial! Grats ;)

My suggestions:
1.
> To run this pipeline on selected GPU we need to adjust the device_id parameter value. Id ordinals are consistent with CUDA device ids. Let's run it on the GPU with ID = 1.

> To run this pipeline on selected GPU we need to adjust the device_id parameter value. ID ordinals are consistent with CUDA device IDs. Let's run it on the GPU with ID = 1.

2. Second code snippet in section **Run pipeline on selected GPU**. Maybe it would be nice to actually view the images, not some enigmatic text like `<nvidia.dali.backend_impl.TensorListGPU object at 0x7f76941c91b8>`? I'd vote for it.
Same for the 3rd snippet in **Sharding** paragraph.

3. sharding.png is not viewing?
image

4.
> Let's take a quick look at the documentation of FileReader look for those parameters.
> Let's take a quick look at those parameters in the documentation for FileReader.

5. The snippet after `help(ops.FileReader)`. Maybe it would be nice to not actually run this snippet, but to add a cell with markdown after this one, with following contents:
```
[...]
 |  `num_shards` : int, optional, default = 1
 |                 Partition the data into this many parts (used for multiGPU training).
[...]
 |  `shard_id` : int, optional, default = 0
 |               Id of the part to read
[...]
```

**Comment by awolant** [comment]
@szalpal Thanks :)

All done.

**Comment by awolant** [comment]
!build

**Pull request merged**
