### PR TITLE
Improve error message when unable to set CPU affinity

### PR DESCRIPTION
**Pull request by jantonguirao**
Signed-off-by: Joaquin Anton <janton@nvidia.com>

### CODE REVIEW

**Comment by jantonguirao** [comment]
!build

**Comment by jantonguirao** [comment]
!build

**Comment by jantonguirao** [comment]
!build

**Comment by klecki** [comment]
**CI MESSAGE**: [707505]: BUILD STARTED

**Comment by klecki** [comment]
**CI MESSAGE**: [707504]: BUILD PASSED

**Comment by klecki** [comment]
**CI MESSAGE**: [707505]: BUILD PASSED

**Pull request merged**
