### PR TITLE
Bump protobuf version in docs

### PR DESCRIPTION
**Pull request by awolant**
Signed-off-by: Albert Wolant <awolant@nvidia.com>

#### Why we need this PR?
- Refactoring to improve docs - adjust protobuf version. It now states supported version - the one we test against.

#### What happened in this PR?
 - What solution was applied:
     *NA*
 - Affected modules and functionalities:
     *Changed protobuf version in docs*
 - Key points relevant for the review:
     *NA*
 - Validation and testing:
     *NA*
 - Documentation (including examples):
     *Yes*

**JIRA TASK**: *[NA]*

### CODE REVIEW

**Comment by awolant** [comment]
!build

**Comment by JanuszL** [comment]
Maybe we can use https://cmake.org/cmake/help/v3.0/module/CheckPrototypeDefinition.html to detect which version of `SetTotalBytesLimit` is available and use either two or single argument variant?

**Comment by JanuszL** [comment]
> 
> 
> Maybe we can use https://cmake.org/cmake/help/v3.0/module/CheckPrototypeDefinition.html to detect which version of `SetTotalBytesLimit` is available and use either two or single argument variant?

But on the other hand we are not testing this and we can easily break it.
:+1:

**Comment by MohamadHalwani** [comment]
same issue here error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, const int&)’

Any help ?

**Comment by JanuszL** [comment]
Hi @MohamadHalwani,

Could you be more specific about what steps you have performed that cause this error?

**Comment by horwina** [comment]
Hi, I am also having this problem and would appreciate feedback.

- Ran make -j'nproc' in Openpose root's build:
~/openpose$ cd  build/
~/openpose/build$ make -j`nproc`

- Returns:
...
[ 76%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/db_lmdb.cpp.o
[ 78%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/hdf5.cpp.o
[ 78%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/im2col.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/insert_splits.cpp.o
[ 79%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/math_functions.cpp.o
[ 81%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/signal_handler.cpp.o
[ 82%] Building CXX object src/caffe/CMakeFiles/caffe.dir/util/upgrade_proto.cpp.o
/home/student/openpose/3rdparty/caffe/src/caffe/util/io.cpp: In function ‘bool caffe::ReadProtoFromBinaryFile(const char*, google::protobuf::Message*)’:
/home/student/openpose/3rdparty/caffe/src/caffe/util/io.cpp:57:66: error: no matching function for call to ‘google::protobuf::io::CodedInputStream::SetTotalBytesLimit(const int&, int)’
   coded_input->SetTotalBytesLimit(kProtoReadBytesLimit, 536870912);
                                                                  ^
In file included from /home/student/openpose/3rdparty/caffe/src/caffe/util/io.cpp:2:0:
/usr/local/include/google/protobuf/io/coded_stream.h:401:8: note: candidate: void google::protobuf::io::CodedInputStream::SetTotalBytesLimit(int)
   void SetTotalBytesLimit(int total_bytes_limit);
        ^~~~~~~~~~~~~~~~~~
/usr/local/include/google/protobuf/io/coded_stream.h:401:8: note:   candidate expects 1 argument, 2 provided
src/caffe/CMakeFiles/caffe.dir/build.make:1461: recipe for target 'src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o' failed
make[5]: *** [src/caffe/CMakeFiles/caffe.dir/util/io.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:350: recipe for target 'src/caffe/CMakeFiles/caffe.dir/all' failed
make[4]: *** [src/caffe/CMakeFiles/caffe.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/openpose_lib.dir/build.make:85: recipe for target 'caffe/src/openpose_lib-stamp/openpose_lib-build' failed
make[2]: *** [caffe/src/openpose_lib-stamp/openpose_lib-build] Error 2
CMakeFiles/Makefile2:82: recipe for target 'CMakeFiles/openpose_lib.dir/all' failed
make[1]: *** [CMakeFiles/openpose_lib.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by JanuszL** [comment]
@horwina - I don't think your issue is related to DALI. What I can suggest is:
- ask https://github.com/CMU-Perceptual-Computing-Lab/openpose authors
- adjust your protobuf version (I guess you have a too old one)

**Comment by horwina** [comment]
@JanuszL Protobuf is newest version
Screen Shot 2021-08-30 at 7 34 41 AM

**Comment by JanuszL** [comment]
@horwina - how about libprotobuf-dev itself? The function should be [there](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L402). You can examine available protobuf headers and see if it is there.

**Comment by horwina** [comment]
@JanuszL Thank you for this suggestion. Libprotobuf-dev is already the latest version as well.

Screen Shot 2021-08-30 at 7 45 18 AM

The problem is that SetTotalBytesLimit expects one argument, in the Protobuf link you just sent
https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/io/coded_stream.h#L402

Whereas caffe's io.cpp expects 2
https://github.com/BVLC/caffe/blob/master/src/caffe/util/io.cpp#L57

**Comment by JanuszL** [comment]
Apparently, it was changed in https://github.com/protocolbuffers/protobuf/commit/92a7e778e7394386f413cec28d67a07630f784b1, So you need either update the compiled code or downgrade the protobuf version.

**Pull request merged**
