### PR TITLE
Docker multi-stage build for CUDA

### PR DESCRIPTION
**Pull request by szalpal**
> What is this change?

Using docker multi-stage build for CUDA dependencies
> What does it fix?
1. No `if ... elif ... elif ... else` syntax for multiple CUDA versions
2. Complying with [docker good practices](https://docs.docker.com/develop/develop-images/multistage-build/)
3. In future, can get rid of 2 dockerfiles (Dockerfile & Dockerfile.deps)
4. Applying _lets include only what we need policy_, in the opposite to _lets exclude everything, that we don't need_ in Dali dependencies
5. Less rebuilds in some scenarios
> Is this a bug fix or a feature? 

Feature
> Does it break any existing functionality or force me to update to a new version?

Transparent to developer
> How has it been tested?

CI [#661798](https://gitlab-master.nvidia.com/dl/dali/dali-gh-mirror/pipelines/661798)

Signed-off-by: Michał Szołucha <mszolucha@nvidia.com>

### CODE REVIEW

**Comment by szalpal** [comment]
> It's clever, but what does it gain, out of curiosity?

In case somebody would like to
```
docker build --build-arg USE_CUDA_VERSION=9 -t dali_deps -f Dockefile.deps .
... do something here ...
docker build --build-arg USE_CUDA_VERSION=10 -t dali_deps -f Dockefile.deps .
```
layer in the image, that adds CUDA, doesn't need to be rebuilt. It just chooses intermediate stage here. Having, in perspective, few more CUDA versions to maintain, makes the `if .. elif .. elif .. else` script more and more spaghetti.
Not to mention, that [docker good practices](https://docs.docker.com/develop/develop-images/multistage-build/) explicitly point out, that the way we currently have is not the best way to do it. I'd imagine, that proper way of managing dependencies in Dali would be to create intermediate stages, where dependency is built and then copying artifacts to target layer. It'd be _lets include only what we need_ policy, versus _lets exclude everything, that we don't need_.

On top of that, I wanted to use multi-stage build for adding DALI_extra to CI, however @JanuszL thinks it's not the way to do it.

**Comment by JanuszL** [comment]
Just reconsidered my opinion. I think it could be a good change.

**Comment by szalpal** [comment]
(#661798)[https://gitlab-master.nvidia.com/dl/dali/dali-gh-mirror/pipelines/661798]

**Comment by szalpal** [comment]
@cliffwoolley @JanuszL , is this OK for you?

**Comment by cliffwoolley** [comment]
One last note on that: multistage docker builds required a reasonably modern version of the docker daemon.  If people complain this doesn't work for them, be sure to check which docker version they have

**Pull request merged**
