### PR TITLE
Replace deprecated fluid APIs to recommended APIs of Paddle

### PR DESCRIPTION
**Pull request by zoooo0820**
## Category:

Other

## Description:

From PaddlePaddle version 2.0, fluid APIs are going to be deprecated. Instead, it is recommended to use more standardized APIs. 

In our plan, fluid APIs will be completely removed in release version 2.6 (and for now, in branch `develop`).  But there are still some fluid case in Paddle plugin of DALI,  leading to an error when Paddle and DALI are used at the same time.

In this PR, the fluid cases are replaced by corresponding standardized APIs, and the function is not changed.

Expected compatibility of DALI and Paddle：
- **DALI <=1.29** :  works well with Paddle <=2.5, but will raise error from Paddle 2.6. (since `paddle.fluid.xxx` are **not available** from 2.6)
- **future release of DALI**: works well with Paddle 2.x. (since the standardized APIs are available in past and future Paddle)

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [x] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by JanuszL** [comment]
Hi @zoooo0820,

Thank you for your contribution. The changes look good.
Can you tell me what is the minimal PaddlePaddle version that is compatible with this change? Maybe you should add an assertion checking the PaddlePaddle version the user has installed and error out if it is too low.

**Comment by JanuszL** [comment]
!build

**Comment by zoooo0820** [comment]
> Hi @zoooo0820,
> 
> Thank you for your contribution. The changes look good. Can you tell me what is the minimal PaddlePaddle version that is compatible with this change? Maybe you should add an assertion checking the PaddlePaddle version the user has installed and error out if it is too low.

Hi @JanuszL , 
Thanks for your advice. The minimal version of Paddle is 2.0 or develop (0.0.0),  I just add a check in this file, please review if this is ok.

**Comment by JanuszL** [comment]
> > Hi @zoooo0820,
> > Thank you for your contribution. The changes look good. Can you tell me what is the minimal PaddlePaddle version that is compatible with this change? Maybe you should add an assertion checking the PaddlePaddle version the user has installed and error out if it is too low.
> 
> Hi @JanuszL , Thanks for your advice. The minimal version of Paddle is 2.0 or develop (0.0.0), I just add a check in this file, please review if this is ok.

Yes. That is perfect. Thanks!

**Comment by JanuszL** [comment]
!build

**Comment by zoooo0820** [comment]
Hi @JanuszL  , I see the DCO check failed. Sorry I missed one commit with signed-off. Should I deal this locally and re-push this commit again?

**Comment by JanuszL** [comment]
> Hi @JanuszL , I see the DCO check failed. Sorry I missed one commit with signed-off. Should I deal this locally and re-push this commit again?

Yes, to be 100% compliant, please do so.

**Comment by zoooo0820** [comment]
> > Hi @JanuszL , I see the DCO check failed. Sorry I missed one commit with signed-off. Should I deal this locally and re-push this commit again?
> 
> Yes, to be 100% compliant, please do so.

Done, please start the CI process again, sorry for my missing.

**Comment by JanuszL** [comment]
> > > Hi @JanuszL , I see the DCO check failed. Sorry I missed one commit with signed-off. Should I deal this locally and re-push this commit again?
> > 
> > 
> > Yes, to be 100% compliant, please do so.
> 
> Done, please start the CI process again, sorry for my missing.

All fine. Happens. Thank you for your prompt response.

**Review by JanuszL — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Review by klecki — APPROVED** [review]

**Pull request merged**
