### PR TITLE
Add debug mode tutorial notebook

### PR DESCRIPTION
**Pull request by ksztenderski**
Signed-off-by: ksztenderski <ksztenderski@nvidia.com>

## Category:

**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:

Add tutorial jupyter notebook showing use cases and features of debug mode.

### Tests
- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [x] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by ksztenderski** [comment]
!build

**Comment by ksztenderski** [comment]
!build

**Comment by klecki** [comment]
Also I would add a section about limitations:
* mention the speed impact,
* mention the seeds - it can have different results than regular pipeline,
* mention the execution order
* anything else?

We should also clearly state somewhere, that those operators work only in a scope of the `pipeline_def` and one cannot use them in numpy style for eager execution.

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
!build

**Comment by ksztenderski** [comment]
!build

**Comment by klecki** [comment]
<p>I still would stick with the backend rather than background. Backend sounds both more technical and kinda implies why this happen.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>But backend doesn't imply parallelism while background does.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by klecki** [comment]
<p>So maybe let's find a section which describes how DALI works and why is it fast and link to it, rather than try to explain it here. For the purpose of this tutorial, we need something that explains why the user can't inspect the graph and its values in regular mode.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
!build

**Comment by JanuszL** [comment]
<p>Maybe in the first example it can stay <code>cpu</code>  and add <code>mixed</code>  in the <code>simple_pipeline_with_print</code>  with a note in the text that it works for GPU as well.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ksztenderski** [comment]
<p>Done, but I'm guessing that you might also wanted it to show print on <code>TensorListGPU</code>,  but I intentionally printed <code>jpegs</code>  here so it would take less space.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by JanuszL** [comment]
<p>Up to you.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3648/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by JanuszL — APPROVED** [review]

**Review by klecki — APPROVED** [review]

**Comment by ksztenderski** [comment]
!build

**Pull request merged**
