### PR TITLE
Add acknowledgement for nvCOMP

### PR DESCRIPTION
**Pull request by stiepan**
Signed-off-by: Kamil Tokarski <ktokarski@nvidia.com>

## Category:
**Other** (*e.g. Documentation, Tests, Configuration*)

The inflate operator will introduce [nvCOMP](https://github.com/NVIDIA/nvcomp) dependency for LZ4 decompression.

## Description:
This PR adds to the acknwoledgements the license and the notice files for nvCOMP SDK which is [introduced as a dependency](https://github.com/NVIDIA/DALI/pull/4366).

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [x] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3049

### CODE REVIEW

**Review by awolant — APPROVED** [review]

**Review by jantonguirao — APPROVED** [review]

**Comment by stiepan** [comment]
!build

**Comment by JanuszL** [comment]
Shouldn't we merge it together with the nvCOMP itself?

**Comment by stiepan** [comment]
> Shouldn't we merge it together with the nvCOMP itself?

Is it necessary? I thought it would be less noise for the reviewrs' when the code is disentangled from long licence file. I'll mention the PRs in one another, and merge one by one, starting from the license.

**Comment by JanuszL** [comment]
> > Shouldn't we merge it together with the nvCOMP itself?
> 
> Is it necessary? I thought it would be less noise for the reviewrs' when the code is disentangled from long licence file. I'll mention the PRs in one another, and merge one by one, starting from the license.

Up to you. I just wanted to make the PRs complete, now the code and the legal aspects are separated.

**Pull request merged**
