### PR TITLE
Add missing examples to DALI sphinx docs

### PR DESCRIPTION
**Pull request by szalpal**
#### Why we need this PR?

There were few examples missing from sphinx docs. This PR adds them

### CODE REVIEW

**Comment by szalpal** [comment]
!build

**Comment by awolant** [comment]
There is small problem in formatting of HSV Operator Example to fix, probably this PR is a good place to do it.

**Comment by szalpal** [comment]
> What is the difference between colortwist and hsv operator?
> Why we need to have both of them?

`ColorTwist` is the old version. As we discussed with @mzient when refactoring of ops, the new version has splitted between Hsv ans BrightnessContrast. I could remove `ColorTwist`, however it break public API. I there a way to mark it as `deprecated`?

**Comment by JanuszL** [comment]
> > What is the difference between colortwist and hsv operator?
> > Why we need to have both of them?
> 
> `ColorTwist` is the old version. As we discussed with @mzient when refactoring of ops, the new version has splitted between Hsv ans BrightnessContrast. I could remove `ColorTwist`, however it break public API. I there a way to mark it as `deprecated`?

Yes we have such option in the schema.

**Comment by klecki** [comment]
I would suggest to not add those examples at the top - we start with more generic ones.

**Comment by szalpal** [comment]
> I would suggest to not add those examples at the top - we start with more generic ones.

In my opinion, the whole `examples` structure needs some redesigning. This PR is meant to be a quick fix for missing docs, which are already there. When I get to this, I might propose a new directory structure for the examples (FTR, directory structure needs to reflect docs structure, for the sake of simplicity). Redesigning directory structure is beyond the scope of this PR.

**Comment by JanuszL** [comment]
If we only can fix all warning that pops up during docs build we can enable `werror` and if again we miss adding some example it will blow the build and we will know.

**Pull request closed without merging**
