### PR TITLE
Add DALI Conditionals documentation

### PR DESCRIPTION
**Pull request by klecki**
## Description:
Add a doc for experimental.pipeline_def
Add a section in pipeline.rst for experimental pipeline options. 
Make debug mode a subsection there, add a section for conditionals. 
Add a tutorial with example usage of conditionals and description of the requirements and technical details.

### Affected modules and functionalities:
Documentation, experimental pipeline decorator docs, conditionals docs.

### Tests:

- [x] Existing tests apply
- [x] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [x] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [x] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
<p>Done. Also, added an example.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/4589/discussion/#comment-1402634724'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by klecki** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/4589/discussion/#comment-1402634749'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by klecki** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/4589/discussion/#comment-1402634781'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by jantonguirao — APPROVED** [review]

**Comment by jantonguirao** [comment]
<p>definig still there</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/4589/discussion/#comment-1402634724'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by klecki** [comment]
@jantonguirao 
> definig still there
I just didn't push yet.

**Review by banasraf — APPROVED** [review]

**Comment by klecki** [comment]
!build

**Pull request merged**
