### PR TITLE
Add T5X tutorial

### PR DESCRIPTION
**Pull request by awolant**
## Category:

**New feature** 

## Description:

Adds tutorial on how to connect DALI and T5X. It shows only DALI iterator and points to full training example in JAX-Toolbox

### Key points relevant for the review:

Is it understandable? Grammar, punctuation, typing errors. 

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3744

### CODE REVIEW

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430748'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>This data is a part of main DALI repo as well as the source of this tutorial. So if someone clones the repo and wan't to run this Jupyter notebook it will work. That's why this path is relative like that. </p><p>We do it in other places as well so I think we can leave it for now. If we have some better idea on how to handle that we can do it for all.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430779'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430811'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done. I also moved the <code>.result()</code> call to the code sample immediately below.   </p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430846'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430877'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by szkarpinski** [comment]
<p>Ok, I understand. Thanks!</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1906430779'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by szkarpinski — APPROVED** [review]

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1907974421'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1907974404'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>Done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1907974371'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
<p>I confirmed that the link works in the rendered docs. </p><p> </p><p>There is a small issue with <code>peekable_data_iterator</code> docs. I will fix it in a subsequent PR and add the link to it here if that's ok. </p><p> </p><p> </p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1907974388'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by awolant** [comment]
!build

**Comment by klecki** [comment]
<p>Sure</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/5286/discussion/#comment-1907974388'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
