### PR TITLE
Python operator notebook

### PR DESCRIPTION
**Pull request by banasraf**
#### Why we need this PR?
*Pick one, remove the rest*
- Refactoring to improve Python operator example

#### What happened in this PR?
*Fill relevant points, put NA otherwise. Replace anything inside []*
 - What solution was applied:
     *Rewriting python operator notebook*
 - Affected modules and functionalities:
     *python operator notebook*
 - Key points relevant for the review:
     *python operator notebook*
 - Validation and testing:
     *NA*
 - Documentation (including examples):
     *NA*

**JIRA TASK**: *DALI-1179*

### CODE REVIEW

**Comment by banasraf** [comment]
!build

**Comment by JanuszL** [comment]
Random erase seems to not erase something in each image in the first row:
image

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
!build

**Pull request merged**
