### PR TITLE
Suppress leaks from inside dlopen

### PR DESCRIPTION
**Pull request by szkarpinski**
## Category:

**Bug fix** (*non-breaking change which fixes an issue*)

## Description:

We dlopen things but not dlclose them, so some internal dlopen structures get leaked. This was suppressed in https://github.com/NVIDIA/DALI/pull/4521, but some of the functions listed there got inlined, resulting in new false positives.

In this PR I add `dlopen` to the suppressions list to avoid further false-positives

### Affected modules and functionalities:
Sanitizer CI runs

### Key points relevant for the review:
Maybe suppressing `dlopen` is too wide?

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Review by awolant — APPROVED** [review]

**Comment by szkarpinski** [comment]
@mzient pointed out that `dlopen` calls globals constructors, so if there's any leak in there it'll get suppressed. So I guess suppressing `dlopen` was a bad idea.

**Comment by szkarpinski** [comment]
@awolant @banasraf I changed (https://github.com/NVIDIA/DALI/pull/5245/commits/62256ef38bb92d9355be714141567abadcade814) the suppressions to be more precise, `dlopen` was too broad and might suppress true leaks. I'll run sanitizer build in a moment to see if this still helps.

**Review by JanuszL — APPROVED** [review]

**Comment by szkarpinski** [comment]
After a long rollercoaster of trying different ways to suppress things I came back to the original solution of just suppressing `dlopen` itself and the CI is finally passing :tada: . @JanuszL @awolant is this OK?

**Comment by JanuszL** [comment]
I think we can proceed that way.

**Pull request merged**
