### PR TITLE
Fix last_batch_padded docs

### PR DESCRIPTION
**Pull request by awolant**
Signed-off-by: Albert Wolant <awolant@nvidia.com>

#### Why we need this PR?
- It fixes a bug in `last_batch_padded` docs.

#### What happened in this PR?
 - Were docs and examples updated, if necessary?
Yes

Addresses #1311  

**JIRA TASK**: [NA]

### CODE REVIEW

**Comment by awolant** [comment]
!build

**Comment by JanuszL** [comment]
How about adding some table with the example like:
```
With the data set [1,2,3,4,5,6,7] and the batch size 2:
    fill_last_batch = False, last_batch_padded = True - [7], next iteration will return [1, 2]
    fill_last_batch = False, last_batch_padded = False - [7], next iteration will return [2, 3]
    fill_last_batch = True, last_batch_padded = True - [7, 7], next iteration will return [1, 2]
    fill_last_batch = True, last_batch_padded = False - [7, 1], next iteration will return [2, 3]
```

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
> How about adding some table with the example like:
> 
> ```
> With the data set [1,2,3,4,5,6,7] and the batch size 2:
>     fill_last_batch = False, last_batch_padded = True - [7], next iteration will return [1, 2]
>     fill_last_batch = False, last_batch_padded = False - [7], next iteration will return [2, 3]
>     fill_last_batch = True, last_batch_padded = True - [7, 7], next iteration will return [1, 2]
>     fill_last_batch = True, last_batch_padded = False - [7, 1], next iteration will return [2, 3]
> ```

Done

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Pull request merged**
