### PR TITLE
Fix LookupTable GPU for scalar inputs

### PR DESCRIPTION
**Pull request by jantonguirao**
## Category:

**Bug fix**

## Description:

Fixes a bug in LookupTable GPU operator when processing scalar inputs.
The bug was originally reported here: https://github.com/NVIDIA/DALI/issues/5254

### Affected modules and functionalities:

LookupTable

### Tests:

- [ ] Existing tests apply
- [x] New tests added
  - [x] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3757

### CODE REVIEW

**Comment by jantonguirao** [comment]
!build

**Review by JanuszL — APPROVED** [review]

**Review by mzient — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Pull request merged**
