### PR TITLE
dtype member for TensorList and modify dtype for Tensor

### PR DESCRIPTION
**Pull request by ksztenderski**
Signed-off-by: ksztenderski <ksztenderski@nvidia.com>

## Description
- [ ] **Bug fix** (*non-breaking change which fixes an issue*)
- [x] **New feature** (*non-breaking change which adds functionality*)
- [ ] **Breaking change** (*fix or feature that would cause existing functionality to not work as expected*)
- [ ] **Refactoring** (*Redesign of existing code that doesn't affect functionality*)
- [ ] **Other** (*e.g. Documentation, Tests, Configuration*)

### What happened in this PR

Adds `.dtype` readonly attribute in TensorListCPU/GPU that is `DALIDataType`.
Modifies `.dtype` for TensorCPU/GPU. For Tensors `.dtype` atribute is of type `_DALIDataType` that is a placeholder for `DALIDataType` before we deprecate `tensor.dtype()`.

#### Additional information
- Affected modules and functionalities:

dtype attribute in TensorList and Tensor

- Key points relevant for the review:

### Tests
- [x] Existing tests apply
- [x] New tests added
  - [x] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [x] Documentation updated
  - [x] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by ksztenderski** [comment]
!build

**Comment by ksztenderski** [comment]
!build

**Review by klecki — APPROVED** [review]

**Comment by ksztenderski** [comment]
!build

**Comment by szalpal** [comment]
How can we document `dtype` for the developer? I mean, previously, we had the `dtype()` documented:
obraz
which made it clear, that it is a numpy string. Now, although the `dtype` is added (yes, I know it's not a function anymore), it doesn't appear in the documentation. I believe we should add info there, that it is in fact a `DALIDataType`, since it changed from numpy string.

**Comment by ksztenderski** [comment]
> 

image

I'm not sure if I understand correctly, information about `dtype` is in the documentation, although there is no information that it is `DALIDataType` and there is no info about deprecation of `.dtype()`.

**Comment by ksztenderski** [comment]
!build

**Comment by ksztenderski** [comment]
!build

**Review by szalpal — APPROVED** [review]

**Pull request merged**
