### PR TITLE
Regenerate getting started jupyter examples

### PR DESCRIPTION
**Pull request by JanuszL**
- regenerates getting started jupyter examples to show
  new tensor printing functionality
- reduces images size in the getting started examples to
  reduce overall size

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

## Category:

**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
- regenerates getting started jupyter examples to show
  new tensor printing functionality
- reduces images size in the getting started examples to
  reduce overall size

### Affected modules and functionalities:
- getting started document

### Key points relevant for the review:
- if printing of the tensor content should cause the adjustment of the tutorial text

### Tests
- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [X] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Review by awolant — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
<p>No idea. Let me check that.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3732/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by stiepan — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Review by stiepan — APPROVED** [review]

**Pull request merged**
