### PR TITLE
Pin Numba version to 0.55.2

### PR DESCRIPTION
**Pull request by awolant**
Signed-off-by: Albert Wolant <awolant@nvidia.com>

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by awolant** [comment]
!build

**Review by jantonguirao — APPROVED** [review]

**Comment by klecki** [comment]
I think that we probably can add it in https://github.com/NVIDIA/DALI/blob/main/qa/setup_packages.py to have it restricted just for CUDA 10. If this helps with CI we can merge this one, and adjust to a proper solution in a followup.

**Comment by awolant** [comment]
Agreed. I just wanted to see, if this is the thing that caused the issue with this PR. Probably it could have been a draft.

**Comment by JanuszL** [comment]
> I think that we probably can add it in https://github.com/NVIDIA/DALI/blob/main/qa/setup_packages.py to have it restricted just for CUDA 10. If this helps with CI we can merge this one, and adjust to a proper solution in a follow-up.

I don't think we can limit it to only 10. If you specify the version for 10 and none for 11 all CUDA versions above 10 will use the version defined from 10 (that is the way it was designed so packages for 10 can be installed when CUDA 10.1 is present in the system).
Maybe we can limit this promotion only to minor versions. 10.2->10 but 11 won't be downgraded.

**Comment by awolant** [comment]
We'll have to pin it for 11 as well, because current version (0.56.0) is the last that supports Python < 3.11.

**Review by klecki — APPROVED** [review]

**Pull request merged**
