### PR TITLE
Hide internal CPUStage/GPUStage operators for nvJPEGDecoder

### PR DESCRIPTION
**Pull request by jantonguirao**
Signed-off-by: Joaquin Anton <janton@nvidia.com>

### CODE REVIEW

**Comment by jantonguirao** [comment]
Build 674355

**Comment by JanuszL** [comment]
I have checked build output and it doesn't work.

**Comment by JanuszL** [comment]
Fixed in https://github.com/NVIDIA/DALI/pull/656.

**Comment by jantonguirao** [comment]
leaving this to #652

**Comment by jantonguirao** [comment]
leaving this to #652

**Pull request closed without merging**
