### PR TITLE
[WIP] RNN-T Model with DALI preprocessing

### PR DESCRIPTION
**Pull request by szalpal**
**If you want to review this, consider looking onto #1745 first**

This is the RNNT implementation, with the data preprocessing pipeline implemented in DALI.

This is only single-GPU. Multi-GPU is a little bit complicated, because of the existing implementation.

This is a gigantic PR, here're the things, that are relevant (i.e. differ from original reference implementation):
1. `dali.py`
2. `train.py`, the part around line 190 and around line 334
3. `scripts/train_dali.sh`
4. `index.rst`
5. `dali_preprocess_librispeech.sh`

TODO left in this PR:
- [ ] Add script to test 1 epoch of RNNT in CI
- [ ] Figure out, if there should be some acknowledgments or ant other licensing issues
- [ ] Figure out, if Multi-GPU can be added in this PR, or does it need another PR
- [ ] Figure out, if the transposition (occurring outside DALI right now) can be done inside DALI
- [ ] Consider expanding to a dataset larger than train-100
- [ ] When DALI is on, native preprocessing is not needed. Consider if it can be decently turned off

### CODE REVIEW

**Comment by mzient** [comment]
I feel uncomfortable with this PR - not because of the size, but because the code is a snapshot from a project still in development elsewhere. The value of this code will decline as it diverges from upstream implementation.
Making it a part of examples is OK only as long as it's easy to run, maintained and properly documented - which may not be a justifiable effort on our side.
If the code is not usable as an example, then maybe we should just move it somewhere to `qa` and strip it down to the bare minimum required to run the tests.
Any ideas on improving this kind of tests is more than welcome.

**Comment by JanuszL** [comment]
> I feel uncomfortable with this PR - not because of the size, but because the code is a snapshot from a project still in development elsewhere. The value of this code will decline as it diverges from upstream implementation.
> Making it a part of examples is OK only as long as it's easy to run, maintained and properly documented - which may not be a justifiable effort on our side.
> If the code is not usable as an example, then maybe we should just move it somewhere to `qa` and strip it down to the bare minimum required to run the tests.
> Any ideas on improving this kind of tests are more than welcome.

I think we can put it here as it is. When the final version of RNNT is ready we can update. I would avoid doing something in the middle. The reason why we should consider having it as it is now is that we need to have something we could test our audio pipeline with.
In the readme I would focus on the data pipeline side, not the model itself.

**Comment by szalpal** [comment]
I essentially agree with that statement (i.e. being uncomfortable to add this to DALI repo). But first things first:
This **is** easy to run. You just need a dataset (which I prepared and is to use all the time) and you trigger `bash scripts/train_dali.sh`. That's it. Maintnance, well, this will be hard.

After all, it's RNNT what depends on DALI, not the other way around. So the RNNT repo should contain integration test, that verifies against versions of DALI. That being said, prolly we should get rid of such test in the first place. However, I wouldn't like to leave this RNNT to rot on my fork somewhere. Will try to figure something out.

**Comment by szalpal** [comment]
This model got out of scope, closing PR

**Pull request closed without merging**
