### PR TITLE
Rework DALI examples to use native PyTorch amp

### PR DESCRIPTION
**Pull request by JanuszL**
- as NVIDIA apex functionality has been incorporated
  into the mainstream PyTorch use it instead of apex

## Category:
**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
- as NVIDIA apex functionality has been incorporated
  into the mainstream PyTorch use it instead of apex

### Affected modules and functionalities:
- RN50 and SSD PyTorch examples

### Key points relevant for the review:
- NA

### Tests:

- [x] Existing tests apply
  - TL1_ssd_training
  - TL3_SSD_convergence
  - TL3_RN50_convergence
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [x] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3274

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Review by jantonguirao — APPROVED** [review]

**Review by awolant — APPROVED** [review]

**Pull request merged**
