### PR TITLE
Generalize `__module__` handling and hide private modules from Ops doc

### PR DESCRIPTION
**Pull request by klecki**
## Description:
Fix for the documentation rendering / `__module__` visibility.

After refactoring, the documentation for ops API started listing all the internall modules. Modules that start with `_` are no longer visible in Sphinx doc.

Moving the custom operator classes to the dedicated submodules casued the docs to render the path to the implementation module and not the one we want to present in the API - due to the `__module__` change.

As the module with the original implementation is still useful, a generalized way of adjusting the `__module__` was introduced, keeping the original information in the operator under _impl_module`.

### Affected modules and functionalities:
Doc generation, `__module__` for operator classes: TFRecordReader, Python Functions, compose.

### Key points relevant for the review:
Please check the legacy API documentation rendering.

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [x] Other - *doc generation updated, pleas check*
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Review by awolant — APPROVED** [review]

**Comment by klecki** [comment]
!build

**Comment by klecki** [comment]
!build

**Pull request merged**
