### PR TITLE
Add examples of processing video with using per-frame

### PR DESCRIPTION
**Pull request by stiepan**
Signed-off-by: Kamil Tokarski <ktokarski@nvidia.com>

## Category:

**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
Adds notebook that presents example of using gaussian blur, rotate and warp operators in video processing pipeline that utilizes per-frame operator. Refers to the notebook in appropriate operators.

## Additional information:

Instead of images, I added gifs to hopefully better visualize video processing results. Hope it is not too heavy on the eyes (and transfer).
### Tests
- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [x] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [x] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-2790

### CODE REVIEW

**Comment by awolant** [comment]
Nice idea with using GIFs for visualization.

**Review by awolant — APPROVED** [review]

**Comment by stiepan** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by stiepan** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by stiepan** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by stiepan** [comment]
<p>:)</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by banasraf** [comment]
<p>For me the fn.per_frame makes most sense directly in the argument - it shows that it's just a marker indicating how the arg should be used.</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by banasraf** [comment]
<p>Those are some serious powerpoint animation effects :p </p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Review by banasraf — APPROVED** [review]

**Comment by stiepan** [comment]
<p>done</p>

---

 <a href='https://app.reviewnb.com/NVIDIA/DALI/pull/3917/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by stiepan** [comment]
!build

**Comment by stiepan** [comment]
!build

**Pull request merged**
