### PR TITLE
CPU versions of Crop/CropCastPermute operators

### PR DESCRIPTION
**Pull request by drivanov**
Signed-off-by: Andrei <andreii@nvidia.com>

### CODE REVIEW

**Review by cliffwoolley — COMMENTED** [review]
Please include the copyright notice from half.hpp in Acknowledgements.txt.  Other than that LGTM

**Review by JanuszL — APPROVED** [review]

**Comment by JanuszL** [comment]
Builds 35246.

**Comment by JanuszL** [comment]
Can you try to use F16C, like https://blogs.msdn.microsoft.com/chuckw/2012/09/11/directxmath-f16c-and-fma/. Otherwise as @ptrendx pointed out we would be very slow due to conversions.

**Comment by drivanov** [comment]
@JanuszL: OK, I will take a look on this approach when I am done with the tasks I am currently working on.

**Comment by ptrendx** [comment]
Build 36028

**Comment by JanuszL** [comment]
Following @ptrendx suggestion lets do F16C in separate commit.

**Pull request merged**
