### PR TITLE
Add link to functions in operator table in docs

### PR DESCRIPTION
**Pull request by JanuszL**
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by JanuszL** [comment]
It looks now like this:
screenshot from 2019-02-08 08-17-00

**Comment by JanuszL** [comment]
Builds 627366

**Comment by klecki** [comment]
I would think about some grouping of the Ops in the docs, similar way as in the source code, i.e. Readers, Geometric, Support, Resize, etc.

**Comment by JanuszL** [comment]
> I would think about some grouping of the Ops in the docs, similar way as in the source code, i.e. Readers, Geometric, Support, Resize, etc.

For that we need to add more info to schema.

**Pull request merged**
