### PR TITLE
Add supported device by every operator to docs

### PR DESCRIPTION
**Pull request by JanuszL**
- adds a table with the mapping between devices and ops
- adds info at each operator about supported device

Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by JanuszL** [comment]
Another build 39987

**Comment by JanuszL** [comment]
screenshot from 2018-11-27 13-01-30

**Comment by JanuszL** [comment]
@Kh4L - what particular you have in mind? By default we have Striped Tables, but any suggestion what and how to do it would be more than welcome.

**Comment by klecki** [comment]
@JanuszL The table looks ok, but I would suggest centering the `X` (or using a tick or something). 

Also description/legend how to understand the columns of the table would be nice.

**Comment by Kh4L** [comment]
@JanuszL I was talking about the `adds info at each operator about supported device` part. Something like colored backgroud for each Device tag (like green for GPU and blue for CPU).

**Comment by JanuszL** [comment]
@klecki - I think I can center that easily, I can try to put "tick" but I don't know how well it will look like.
@Kh4L - I don't know if I can add theme to only this part, it is basically rst that depending on function gets different theme. I think I cannot create something custom just to get it colored. What we have is just http://docutils.sourceforge.net/docs/user/rst/quickref.html and if I change theme of one thing it will affect all other occurrence of it. Nevertheless I may be completely wrong as I'm not sphinx, rst nor css expert. So any hint is more than welcome.

**Comment by JanuszL** [comment]
How about now?:
screenshot from 2018-11-30 08-42-29
screenshot from 2018-11-30 08-43-08

**Comment by JanuszL** [comment]
Builds 40352

**Comment by klecki** [comment]
@JanuszL, table looks great. 
I would suggest something like list at the top:
**Operator type:** `CPU`, `GPU`
with similar styling, but you may leave it as it is.

**Pull request merged**
