### PR TITLE
Port operators Python tests to `nose2`

### PR DESCRIPTION
**Pull request by awolant**
Signed-off-by: Szymon Karpiński <skarpinski@nvidia.com>

## Category:

Refactoring

## Description:

Moves all operator tests from `nose` to `nose2`. Two main things were done in this PR:
- bash scripts used to run the tests were adjusted to run python operator tests with `nose2`
- tests were adjusted to be compatible with `nose2` 

### Affected modules and functionalities:

Python tests for operators.

### Key points relevant for the review:

Are all tests ported without loosing any test or test coverage.

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-2872

### CODE REVIEW

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Comment by awolant** [comment]
!build

**Review by prak-nv — APPROVED** [review]

**Review by banasraf — APPROVED** [review]

**Pull request merged**
