### PR TITLE
Fix TF 1.11 compatibility

### PR DESCRIPTION
**Pull request by JanuszL**
Signed-off-by: Janusz Lisiecki <jlisiecki@nvidia.com>

### CODE REVIEW

**Comment by JanuszL** [comment]
This is ugly hack as it removes proper error reporting in TF, but they changed constructor of error status which is not compatible between 1.11 and older releases. So let me remove it and see if it is compatible again.

**Comment by JanuszL** [comment]
Testing 37543.

**Comment by JanuszL** [comment]
No, everything what uses any string - like GetAttr will won't work.
I think we are not able to make it compatible with 1.11 and older one in the same build

**Comment by JanuszL** [comment]
Rebuild 37778

**Comment by JanuszL** [comment]
Added 1.12.rc1 test - rebuilds 37781.

**Comment by JanuszL** [comment]
Fix for 1.12.rc1 builds 37870.

**Comment by bhack** [comment]
rc2

**Comment by JanuszL** [comment]
Builds 38088

**Comment by JanuszL** [comment]
I want to merge #255 to shorten tests.

**Comment by JanuszL** [comment]
Rebuilding on 38144.

**Pull request merged**
