### PR TITLE
Add the seqence reader example

### PR DESCRIPTION
**Pull request by kychennv**
add sequence_reader_simple_example

### CODE REVIEW

**Comment by kychennv** [comment]
> Thanks for the fine example, only few minor comments from my side.

please help to check

**Comment by JanuszL** [comment]
- direcotry -> directory
- 0/1.png,0/2.png,,,1/,2/ ?
- Then, Create SequencePipeline We will use matplotlib to display the frames we obtained -> 
Then, after creating SequencePipeline we will use matplotlib to display the frames we obtained
- Build and run the pipe line, show all of the sequcenes from the batchs -> Now let's build and run the pipeline so we can show all of the sequences from the batch
- please include this in docs/examples/dataloading.rst so documentation will show that as wel

**Comment by kychennv** [comment]
> * direcotry -> directory
> * 0/1.png,0/2.png,,,1/,2/ ?
> * Then, Create SequencePipeline We will use matplotlib to display the frames we obtained ->
>   Then, after creating SequencePipeline we will use matplotlib to display the frames we obtained
> * Build and run the pipe line, show all of the sequcenes from the batchs -> Now let's build and run the pipeline so we can show all of the sequences from the batch
> * please include this in docs/examples/dataloading.rst so documentation will show that as wel

done. thanks for your help

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by mzient** [comment]
1. It may not be a problem with this PR _per se_, but the dumped sequences always contain duplicated first frame (0.png is identical to 1.png).
2. I'd be happier if the temporary files were put into something more explicitly temporary than `[DALI_extra]/db/sequence_reader`, e.g. `[DALI_extra]/tmp/sequence_reader`. Using system temporary directory might have its advantages, but comes at a price of making the files harder to access for the user. If using `[DALI_extra]/tmp`, it should be added to .gitignore in `DALI_extra`.

**Comment by JanuszL** [comment]
>     1. It may not be a problem with this PR _per se_, but the dumped sequences always contain duplicated first frame (0.png is identical to 1.png).
> 

Maybe it is better to use ffmpeg to extract frames from the video to avoid this kind of Video reader dependency.

>     2. I'd be happier if the temporary files were put into something more explicitly temporary than `[DALI_extra]/db/sequence_reader`, e.g. `[DALI_extra]/tmp/sequence_reader`. Using system temporary directory might have its advantages, but comes at a price of making the files harder to access for the user. If using `[DALI_extra]/tmp`, it should be added to .gitignore in `DALI_extra`.

I don't know if polluting `DALI_extra` is a good idea either. Maybe in the current example dir?

**Comment by mzient** [comment]
I found out that it was the mp4 file that was broken. I posted a PR to DALI_extra with a new version of the file.

**Comment by JanuszL** [comment]
Just regenerated the example with a few more fixes.

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Comment by klecki** [comment]
Some minor nitpicks: in the notebook snippets, sometime there is 
`variable=value` and the rest of the times `variable = value`.

**Comment by JanuszL** [comment]
Done

**Comment by JanuszL** [comment]
!build

**Pull request merged**
