### PR TITLE
Extend the external source signature to include all arguments

### PR DESCRIPTION
**Pull request by JanuszL**
- adds missing arguments to the external source function signature

## Category:
**Other** (*e.g. Documentation, Tests, Configuration*)

## Description:
- adds missing arguments to the external source function signature

### Affected modules and functionalities:
- external_source.py

### Key points relevant for the review:
- if any other argument is missing

### Tests:

- [x] Existing tests apply
  - test_external_source
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [x] Documentation updated
  - [x] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Comment by JanuszL** [comment]
!build

**Review by jantonguirao — APPROVED** [review]

**Comment by klecki** [comment]
This doesn't do anything that the description advertises. It's just signature of an internal helper function and we moved those arguments from being passed as `kwargs` to being explicitly passed.
You would need to adjust it here: https://github.com/JanuszL/DALI/blob/extend_es_docs/dali/python/nvidia/dali/external_source.py#L993 - indeed, those are missing, but we have them specified in the interface: https://github.com/JanuszL/DALI/blob/extend_es_docs/dali/python/nvidia/dali/external_source.pyi

**Comment by JanuszL** [comment]
!build

**Comment by JanuszL** [comment]
> This doesn't do anything that the description advertises. It's just signature of an internal helper function and we moved those arguments from being passed as `kwargs` to being explicitly passed. You would need to adjust it here: https://github.com/JanuszL/DALI/blob/extend_es_docs/dali/python/nvidia/dali/external_source.py#L993 - indeed, those are missing, but we have them specified in the interface: https://github.com/JanuszL/DALI/blob/extend_es_docs/dali/python/nvidia/dali/external_source.pyi

I fixed it in other place. The reason of this PR is missing args in the function prototype in the docs - https://docs.nvidia.com/deeplearning/dali/user-guide/docs/operations/nvidia.dali.fn.external_source.html. PYI seems to be not used by Sphinx.

**Review by klecki — APPROVED** [review]

**Comment by JanuszL** [comment]
!build

**Pull request merged**
