### PR TITLE
Extend supported ops doc to include info about volumetric data. 

### PR DESCRIPTION
**Pull request by banasraf**
Signed-off-by: Rafal <Banas.Rafal97@gmail.com>

#### Why we need this PR?
- It extends documentation of operators to include info about the support of  3D data.

#### What happened in this PR?
 - Explain solution of the problem, new feature added.
   It adds a property to `OpSchema`. Support of volumetric data can be also inferred from the accepted input layouts.
 - Was this PR tested? How?
   Checked how the documentation is rendered. 
 - Were docs and examples updated, if necessary?
   YES

image

**JIRA TASK**: [DALI-1161]

### CODE REVIEW

**Comment by banasraf** [comment]
!build

**Comment by banasraf** [comment]
Screenshot_2019-12-03 Supported operations — NVIDIA DALI 0 17 0dev documentation
Full supported ops table

**Comment by banasraf** [comment]
Screenshot_2019-12-03 Supported operations — NVIDIA DALI 0 17 0dev documentation(1)
Full supported ops table

**Comment by jantonguirao** [comment]
@banasraf There are some operators that would work with sequences and volumetric data, because they treat the data as a 1D tensor, and are not marked as so. One example is `LookupTable`

**Comment by banasraf** [comment]
!build

**Pull request merged**
