### PR TITLE
VideoReader stride

### PR DESCRIPTION
**Pull request by Kh4L**
- Add a `stride` argument (default 1): Extracted sequence of size `n` and stride `s` starting at frame 'f' is now the following sequence:
```
[f, f+s*1, f+s*2 ... f + s*(n-1)]
```
- Add Python test units for VideoReader based pipeline for L0 tests

### CODE REVIEW

**Comment by Kh4L** [comment]
Build 699370

**Comment by Kh4L** [comment]
!build

**Comment by Kh4L** [comment]
!build

**Comment by Kh4L** [comment]
!build

**Comment by Kh4L** [comment]
!build

**Comment by JanuszL** [comment]
!build

**Pull request merged**
