### PR TITLE
Add setuptools to install_requires for Python 3.12

### PR DESCRIPTION
**Pull request by weiji14**
## Category:

Bug fix

## Description:

Fix `ModuleNotFoundError: No module named 'distutils'` on Python 3.12, since `distutils` is vendored by setuptools now (see https://peps.python.org/pep-0632/). This is on `nvidia-dali-cuda120=1.42.0` installed from https://pypi.nvidia.com/nvidia-dali-cuda120/

```python-traceback
Python 3.12.5 | packaged by conda-forge | (main, Aug  8 2024, 18:36:51) [GCC 12.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nvidia.dali
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/__init__.py", line 20, in <module>
    from . import ops
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/ops/__init__.py", line 25, in <module>
    from nvidia.dali import fn as _functional
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/fn/__init__.py", line 19, in <module>
    from nvidia.dali.external_source import external_source
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/external_source.py", line 19, in <module>
    from nvidia.dali import _autograph
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/_autograph/__init__.py", line 39, in <module>
    from nvidia.dali._autograph.impl.api import initialize_autograph
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/_autograph/impl/api.py", line 54, in <module>
    from nvidia.dali._autograph.pyct import transpiler
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/_autograph/pyct/transpiler.py", line 24, in <module>
    from nvidia.dali._autograph.pyct import gast_util
  File "/home/user/project/.venv/lib/python3.12/site-packages/nvidia/dali/_autograph/pyct/gast_util.py", line 21, in <module>
    from distutils.version import LooseVersion
ModuleNotFoundError: No module named 'distutils'
```

References:
- https://setuptools.pypa.io/en/stable/deprecated/distutils-legacy.html#prefer-setuptools

### Affected modules and functionalities:

- Adds `setuptools` as a dependency for Python 3.12 and above

### Key points relevant for the review:

See if the syntax in `dali/python/setup.py.in` looks correct.

### Tests:

- [ ] Existing tests apply
- [ ] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [ ] N/A

**REQ IDs**: N/A

**JIRA TASK**: N/A

### CODE REVIEW

**Review by mzient — APPROVED** [review]

**Comment by stiepan** [comment]
!build

**Comment by weiji14** [comment]
> I think we will need to properly depart from distutils in favour of setuptools, in the meantime it seems the distutils shipped with setuptools works fine. Let me run the changes through CI.

Cool, let's see how CI goes first. According to the [migration guide](https://setuptools.pypa.io/en/stable/deprecated/distutils-legacy.html#prefer-setuptools), `distutils.version.*` would need to be replaced with [`packaging.version.*`](https://packaging.pypa.io/en/latest/version.html) rather than setuptools, so it'll be a bit more involved, but there's no rush to do that yet.

**Comment by stiepan** [comment]
Hi @weiji14,

We are building for Python 3.12, but it looks like we had the setuputils installed in the CI env thus not catching the bug.

I see @JanuszL prepared a PR that departs from using the distutils in the code, https://github.com/NVIDIA/DALI/pull/5679.

**Comment by weiji14** [comment]
Nice, I see that happening over at https://github.com/NVIDIA/DALI/pull/5687. That should get rid of all the deprecation warnings. Feel free to close this PR once that migration from `distutils` to `packaging` is done.

**Comment by JanuszL** [comment]
We just merged https://github.com/NVIDIA/DALI/pull/5687. I'm sorry we are not moving forward with your PR, on the other hand your effort sparked the change in the right direction. Thank you again for your time and involvement.

**Comment by weiji14** [comment]
No worries, I'd much rather see the deprecation warnings go away! Will look forward to seeing the next release.

**Pull request closed without merging**
