### PR TITLE
Add fn.experimental.crop_mirror_normalize

### PR DESCRIPTION
**Pull request by jantonguirao**
## Category:

**New feature** 

## Description:

- new experimental implementation of GPU CropMirrorNormalize: `fn.experimental.crop_mirror_normalize`
- Optimizes the HWC and CHW cases
- Fallback to the old implementation for less common cases

### Affected modules and functionalities:

- new op

### Key points relevant for the review:

- Implementation

### Tests:

- [x] Existing tests apply
- [ ] New tests added
  - [x] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A
All existing CMN tests were applied to this op as well.

### Documentation
- [x] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [ ] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3069

### CODE REVIEW

**Comment by jantonguirao** [comment]
!build

**Comment by jantonguirao** [comment]
!build

**Comment by jantonguirao** [comment]
!build

**Review by awolant — APPROVED** [review]

**Comment by jantonguirao** [comment]
!build

**Comment by jantonguirao** [comment]
!build

**Review by szalpal — APPROVED** [review]

**Pull request merged**
