### PR TITLE
CPU version of CropMirrorNormalize

### PR DESCRIPTION
**Pull request by drivanov**
Besides that:
- fixing problems with checking results the images of different formats and layouts
- DALITest/DALISingleOpTest refactored

Signed-off-by: andreii <andreii@nvidia.com>

### CODE REVIEW

**Review by pribalta — COMMENTED** [review]
I'm currently working on a refactoring of Crop for SSD support, and the changes to the structure of these operators are slowly introducing a problem that it will be increasingly hard to address and that---in the case of Crop---I'm trying to get rid of.

We have basic operators like Crop, which are recombined in other fused operators or couldbe extended by other variants that may provide a different schema or parametrization (Slice for SSD using prospective crops with different area for each input). At the moment, their arguments (CropArgs) are kept as a parent class creating a `is-a` relationship that essentially locks down the ability to extend these operators without adding complexity.

IMHO a good change would be to introduce composition, where arguments can be injected to the operator while providing a predefined interface, that other specializations or extensions of the operator can fill and support, and where the functionality of the operator remains immutable. Adding increasing levels of inheritance to these attributes will increase coupling and bring problems in the future, as the only way to extend these operators will be through hacking SetupSharedParams or DataDependentSetup.

The last definitely is not advisable, as it requires to change the internal state of the Op and might lead to all sorts of different problems, from multithreading issues to unnecessary overhead before each call to RunImpl. In conclusion, I think that constructs like CastPermuteAttr will become limiting and I'd advise to convert them into interfaces that can be injected on construction.

**Comment by JanuszL** [comment]
Code duplication is one thing, but DALI as an FW needs to have the ability to be easily extensible. This approach shrinks code and reduces repetition - what is good, but limits ability to extend it what is bad.
So I want to see some approach that is extensible at the first place, then reduced code repetition as much as possible without hurting the first things.

**Comment by drivanov** [comment]
Since the changes necessary to start using the composition instead of the currently used inheritance can be implemented gradually, and I think that this should be done within the framework of another PR.

This one already contains quite significant changes that are needed in DALI ASAP. Among these changes:
- elimination of problems with the launch of various operators Crop / Cast / Permute / Normalize operators
- verification of test results for images of various formats and layouts (Remember, I've reported a bug regarding the image layout information which was not passed to output tensor or tensor lists?)
- the possibility to support PNG and TIFF encoding tests.

Besides, without this PR, we are not able to use the image representation in int16 / int32 / int64 formats. The only options for Cast we have now are:
- uint8 / float - for CPU / GPU;
- float16 - for GPU only.

**Comment by JanuszL** [comment]
After long discussion we came to the conclusion that we ill merge #257 and rework test in other PRs in more generic way.

**Pull request closed without merging**
