### PR TITLE
Updating default value for crop_pos

### PR DESCRIPTION
**Pull request by szalpal**
(0.5, 0.5) default value for crop in not really usable, since when user doesn't want the cropping (e.g. in fused ops), he needs to have (0.0, 0.0). 

Signed-off-by: Michał Szołucha <mszolucha@nvidia.com>

### CODE REVIEW

**Comment by szalpal** [comment]
!build

**Comment by szalpal** [comment]
!build

**Comment by szalpal** [comment]
!build

**Comment by JanuszL** [comment]
I would run L1, L2 and L3 after L0 passes just in case.

**Pull request closed without merging**
