### PR TITLE
Support checkpointing in JAX peekable iterator

### PR DESCRIPTION
**Pull request by szkarpinski**
## Category:

**New feature** (*non-breaking change which adds functionality*)

## Description:

This PR adds checkpointing support to JAX/CLU peekable iterator. It's an iterator that allows you to look at the data (_peek_) multiple times without actually consuming it. This peeking is implemented by simply keeping the _peeked_ batch inside the iterator and returning it multiple times on multiple calls to `peek`, until it's properly consumed with `next`.

This approach makes checkpointing hard for iterators which have already `peek`ed at the data but didn't consume it. In this PR I raise an error in this case, allowing checkpointing only if no peeked data is kept in the iterator.

Also, I removed `peek` from `__init__`. The `peek` was used there to learn about data type and shape to ensure its consistency. It made the code clean, but put freshly created iterators in non-checkpointable state. I moved the code obtaining data type and shape to the place where the data is actually seen.

### Affected modules and functionalities:

Peekable iterator

### Tests:

- [ ] Existing tests apply
- [x] New tests added
  - [ ] Python tests
  - [ ] GTests
  - [ ] Benchmark
  - [ ] Other
- [ ] N/A

### Documentation
- [ ] Existing documentation applies
- [ ] Documentation updated
  - [ ] Docstring
  - [ ] Doxygen
  - [ ] RST
  - [ ] Jupyter
  - [ ] Other
- [x] N/A

#### Requirements
- [ ] Implements new requirements
- [ ] Affects existing requirements
- [x] N/A

**REQ IDs**: N/A

**JIRA TASK**: DALI-3871

### CODE REVIEW

**Comment by szkarpinski** [comment]
!build

**Comment by szkarpinski** [comment]
!build

**Comment by szkarpinski** [comment]
!build

**Review by jantonguirao — APPROVED** [review]

**Review by klecki — APPROVED** [review]

**Comment by szkarpinski** [comment]
!build

**Pull request merged**
