### PR TITLE
[WIP] Enable eval after epoch in L3 TF RN50

### PR DESCRIPTION
**Pull request by Kh4L**
Signed-off-by: Serge Panev <spanev@nvidia.com>

### CODE REVIEW

**Comment by Kh4L** [comment]
Build 699681

**Comment by Kh4L** [comment]
Job 6087980

**Comment by Kh4L** [comment]
!build

**Comment by Kh4L** [comment]
!build

**Comment by klecki** [comment]
!build

**Comment by JanuszL** [comment]
I think we don't need this after all.

**Pull request closed without merging**
